/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_assginment;


import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
 

/**
 *
 * @author thong
 */
public class Sales_Manager_page extends javax.swing.JFrame {
    
    
    private static final String FILE_Item_Inventory = "src/User_data/ItemInventory.txt";
    private static final String FILE_Daily_Sales = "src/User_data/DailySales.txt";
    private static final String FILE_Requisitions = "src/User_data/Requisitions.txt";
    private static final String FILE_Stock = "src/User_data/Stock_data.txt";
    private final String FILE_Purchase_Order = "src/User_data/PurchaseOrders.txt";
    private final String FILE_Sale_Report = "src/User_data/Sale_report.txt";


    /**
     * Creates new form Sales_Manager_page
     */
    public Sales_Manager_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        View_Items = new javax.swing.JButton();
        Sales_Report = new javax.swing.JButton();
        Check_Stock = new javax.swing.JButton();
        Requisitions = new javax.swing.JButton();
        Purchase_Orders = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        View_Items.setText("View Items ");
        View_Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(View_Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        Sales_Report.setText("Sales Report");
        Sales_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sales_ReportActionPerformed(evt);
            }
        });
        getContentPane().add(Sales_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        Check_Stock.setText("Check Stock ");
        Check_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_StockActionPerformed(evt);
            }
        });
        getContentPane().add(Check_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        Requisitions.setText("Requisitions ");
        Requisitions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequisitionsActionPerformed(evt);
            }
        });
        getContentPane().add(Requisitions, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        Purchase_Orders.setText("Purchase Orders");
        Purchase_Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Purchase_OrdersActionPerformed(evt);
            }
        });
        getContentPane().add(Purchase_Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 710, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thong\\OneDrive - Asia Pacific University\\Documents\\NetBeansProjects\\Java_Assginment\\src\\image_file\\minecraft image.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 740, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Check_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_StockActionPerformed
    File inventoryFile = new File(FILE_Item_Inventory);
    StringBuilder lowStockItems = new StringBuilder();
    boolean lowStockFound = false;

    try (BufferedReader br = new BufferedReader(new FileReader(inventoryFile))) {
        String line;
        while ((line = br.readLine()) != null) {
            try {
                // Assuming format: Date,Item,Quantity Sold,Price per Unit,Total Sales,Initial Stock,Quantity Remain
                String[] data = line.split(",");
                if (data.length != 7) {
                    throw new IllegalArgumentException("Invalid data format.");
                }

                String item = data[1].trim();
                int quantityRemain = Integer.parseInt(data[6].trim());

                // Check if the remaining quantity is below 20
                if (quantityRemain < 20) {
                    lowStockFound = true;
                    lowStockItems.append("Item: ").append(item)
                                 .append(" | Quantity Remain: ").append(quantityRemain)
                                 .append("\n");
                }
            } catch (Exception e) {
                // Log invalid lines (optional)
                System.err.println("Skipped invalid line: " + line);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading the inventory file: " + e.getMessage());
        return;
    }

    // Show low stock items or notify if none are found
    if (lowStockFound) {
        JOptionPane.showMessageDialog(this, "Low Stock Items:\n\n" + lowStockItems.toString(), 
                                      "Low Stock Alert", JOptionPane.WARNING_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "All items have sufficient stock.", 
                                      "Stock Check", JOptionPane.INFORMATION_MESSAGE);
    }
    

    }//GEN-LAST:event_Check_StockActionPerformed

    private void Sales_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sales_ReportActionPerformed
     File itemsFile = new File(FILE_Sale_Report);
    if (itemsFile.exists()) {
        try (BufferedReader br = new BufferedReader(new FileReader(itemsFile))) {
            String line = br.readLine(); // Read the header
            if (line != null) {
                String[] headers = line.split(","); // Split the header for column names
                DefaultTableModel model = new DefaultTableModel(headers, 0); // Create a model with headers

                while ((line = br.readLine()) != null) {
                    String[] row = line.split(","); // Split each row by commas
                    model.addRow(row); // Add row to the model
                }

                jTable1.setModel(model); // Set the model to the JTable
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading items data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Items file not found.");
    }

    }//GEN-LAST:event_Sales_ReportActionPerformed

    private void View_ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_ItemsActionPerformed
     File itemsFile = new File(FILE_Item_Inventory);
    if (itemsFile.exists()) {
        try (BufferedReader br = new BufferedReader(new FileReader(itemsFile))) {
            String line = br.readLine(); // Read the header
            if (line != null) {
                String[] headers = line.split(","); // Split the header for column names
                DefaultTableModel model = new DefaultTableModel(headers, 0); // Create a model with headers

                while ((line = br.readLine()) != null) {
                    String[] row = line.split(","); // Split each row by commas
                    model.addRow(row); // Add row to the model
                }

                jTable1.setModel(model); // Set the model to the JTable
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading items data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Items file not found.");
    }
    

    }//GEN-LAST:event_View_ItemsActionPerformed

    private void Purchase_OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Purchase_OrdersActionPerformed
         String purchaseID = JOptionPane.showInputDialog(this, "Enter Purchase Order ID to verify:");

        if (purchaseID == null || purchaseID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Purchase Order ID cannot be empty.");
            return;
        }

        File poFile = new File(FILE_Purchase_Order); // Example file where POs are stored
        boolean poFound = false;

        try (BufferedReader br = new BufferedReader(new FileReader(poFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.startsWith(purchaseID + ",")) { // Assuming POs are stored as ID,Details
                    poFound = true;
                    break;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading the purchase orders file: " + e.getMessage());
            return;
        }

        if (poFound) {
            JOptionPane.showMessageDialog(this, "Purchase Order " + purchaseID + " verified successfully.");
            // Logic to update status can be added here
        } else {
            JOptionPane.showMessageDialog(this, "Purchase Order ID " + purchaseID + " not found.");
        }
        
        
    }//GEN-LAST:event_Purchase_OrdersActionPerformed

    private void RequisitionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequisitionsActionPerformed
    File inventoryFile = new File(FILE_Item_Inventory);
    File requisitionsFile = new File(FILE_Requisitions);

    StringBuilder requisitionsData = new StringBuilder();
    boolean lowStockFound = false;

    try (BufferedReader br = new BufferedReader(new FileReader(inventoryFile))) {
        String line;
        while ((line = br.readLine()) != null) {
            try {
                // Assuming format: Date,Item,Quantity Sold,Price per Unit,Total Sales,Initial Stock,Quantity Remain
                String[] data = line.split(",");
                if (data.length != 7) {
                    throw new IllegalArgumentException("Invalid data format.");
                }

                String item = data[1].trim();
                int quantityRemain = Integer.parseInt(data[6].trim());

                // Check if the remaining quantity is below 20
                if (quantityRemain < 20) {
                    lowStockFound = true;
                    requisitionsData.append("Item: ").append(item)
                                    .append(" | Quantity Remain: ").append(quantityRemain)
                                    .append("\n");
                }
            } catch (Exception e) {
                // Log invalid lines (optional)
                System.err.println("Skipped invalid line: " + line);
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error reading inventory data: " + e.getMessage());
        return;
    }

    // Write low stock items to Requisitions.txt
    if (lowStockFound) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(requisitionsFile))) {
            bw.write(requisitionsData.toString());
            JOptionPane.showMessageDialog(this, 
                "Requisitions have been successfully recorded in Requisitions.txt.\n\nLow Stock Items:\n" 
                + requisitionsData.toString(), 
                "Requisitions", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing requisitions data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "All items have sufficient stock. No requisitions needed.", 
                                      "Requisitions", JOptionPane.INFORMATION_MESSAGE);
    }
    
    }//GEN-LAST:event_RequisitionsActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to edit.");
        return;
    }
    jTable1.editCellAt(selectedRow, 0); // Puts the first cell in edit mode
    
    
    }//GEN-LAST:event_EditActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{"", "", "", ""}); // Add an empty row with four columns
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        return;
    }
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.removeRow(selectedRow); // Remove the selected row
    
    
    }//GEN-LAST:event_DeleteActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
    File itemsFile = new File(FILE_Item_Inventory);
    try (BufferedWriter bw = new BufferedWriter(new FileWriter(itemsFile))) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Write the header
        for (int col = 0; col < model.getColumnCount(); col++) {
            bw.write(model.getColumnName(col) + (col == model.getColumnCount() - 1 ? "\n" : ","));
        }
        // Write each row
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                bw.write(model.getValueAt(row, col) + (col == model.getColumnCount() - 1 ? "\n" : ","));
            }
        }
        JOptionPane.showMessageDialog(this, "Data saved successfully.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error saving data: " + e.getMessage());
    }
    
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales_Manager_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales_Manager_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Check_Stock;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Purchase_Orders;
    private javax.swing.JButton Requisitions;
    private javax.swing.JButton Sales_Report;
    private javax.swing.JButton Save;
    private javax.swing.JButton View_Items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
